import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { VoiceSelector } from "../components/VoiceSelector";
import { HapticButton } from "../components/HapticButton";
import { cn } from "../lib/utils";

export const Route = createFileRoute("/settings")({
  head: () => ({
    meta: [
      { title: "Settings • GoalBot Radio" },
      { name: "description", content: "Pick your commentary voice. Toggle notifications." },
    ],
  }),
  component: Settings,
});

function Settings() {
  const [notif, setNotif] = useState(true);

  return (
    <div className="px-4 pb-6 pt-5">
      <div className="text-[11px] font-bold uppercase tracking-[0.18em] text-primary">
        Settings
      </div>
      <h1 className="mb-6 text-2xl font-extrabold tracking-tight">Make it yours</h1>

      <section className="mb-7">
        <h2 className="mb-3 text-sm font-bold uppercase tracking-wider text-muted-foreground">
          Commentary voice
        </h2>
        <VoiceSelector />
      </section>

      <section className="mb-7">
        <h2 className="mb-3 text-sm font-bold uppercase tracking-wider text-muted-foreground">
          Notifications
        </h2>
        <div className="flex items-center justify-between rounded-2xl border border-white/8 bg-card p-4">
          <div>
            <div className="text-sm font-semibold">Morning recap</div>
            <div className="text-xs text-muted-foreground">A single nudge. 7:30am, daily.</div>
          </div>
          <HapticButton
            hapticPattern="soft"
            onClick={() => setNotif((n) => !n)}
            aria-pressed={notif}
            className={cn(
              "relative h-7 w-12 rounded-full transition-colors",
              notif ? "bg-primary" : "bg-white/15",
            )}
          >
            <span
              className={cn(
                "absolute top-0.5 h-6 w-6 rounded-full bg-white shadow transition-transform",
                notif ? "translate-x-5" : "translate-x-0.5",
              )}
            />
          </HapticButton>
        </div>
      </section>

      <section className="rounded-2xl border border-white/8 bg-card p-4 text-xs leading-relaxed text-muted-foreground">
        <div className="mb-1 text-sm font-semibold text-foreground">AI disclosure</div>
        Recaps on GoalBot Radio are generated by AI from publicly available match data. Voices are
        synthetic. No copyrighted broadcast audio is used.
      </section>
    </div>
  );
}
